# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.initrd.supportedFilesystems = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b2830b9a-dc4b-45ac-8149-431d7811ed16";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."linux".device = "/dev/disk/by-uuid/7df0e01d-a3c4-4b50-b74c-ad7c41790f4d";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b2830b9a-dc4b-45ac-8149-431d7811ed16";
      fsType = "btrfs";
      options = [ "subvol=@/home" ];
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/b2830b9a-dc4b-45ac-8149-431d7811ed16";
      fsType = "btrfs";
      options = [ "compress,subvol=@/snapshots" ];
    };

  fileSystems."/boot" =
    # { device = "/dev/disk/by-uuid/76A4-2B10";
    { device = "/dev/disk/by-uuid/B1B0-3797";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
